# coding: utf-8

"""
    Site Configuration

    List of APIs used to manage your site specific configuration attributes, and HA configuration for both branch and data center sites.

    The version of the OpenAPI document: Latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lib.api.SiteConfiguration.models.hub_cluster_element import HubClusterElement
from typing import Optional, Set
from typing_extensions import Self

class HubClusterV4(BaseModel):
    """
    HubClusterV4
    """ # noqa: E501
    default_cluster: Optional[StrictBool] = Field(default=None, description="List the details of the default cluster. ")
    description: Optional[Any] = Field(default=None, description="Description of the default cluster. ")
    elements: Optional[List[HubClusterElement]] = Field(default=None, description="Details of the elements in the cluster. ")
    id: Optional[StrictStr] = Field(default=None, description="The ID of the cluster. ")
    name: StrictStr = Field(description="The name of the cluster. ")
    peer_sites: List[StrictStr] = Field(description="The sites associated with the data center cluster. ")
    site_count_alarm_threshold: Optional[StrictInt] = Field(default=None, description="The count threshold of the alarms for the sites. ")
    tags: Optional[List[StrictStr]] = Field(default=None, description="A information field that can be added to identify the hub cluster. ")
    __properties: ClassVar[List[str]] = ["default_cluster", "description", "elements", "id", "name", "peer_sites", "site_count_alarm_threshold", "tags"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HubClusterV4 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in elements (list)
        _items = []
        if self.elements:
            for _item in self.elements:
                if _item:
                    _items.append(_item.to_dict())
            _dict['elements'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HubClusterV4 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "default_cluster": obj.get("default_cluster"),
            "description": obj.get("description"),
            "elements": [HubClusterElement.from_dict(_item) for _item in obj["elements"]] if obj.get("elements") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "peer_sites": obj.get("peer_sites"),
            "site_count_alarm_threshold": obj.get("site_count_alarm_threshold"),
            "tags": obj.get("tags")
        })
        return _obj


